server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestao_estagio_backend}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  servlet:
    multipart:
      max-file-size: 5MB
  flyway:
    placeholder-replacement: false
application:
  jwt:
    secretKey: ${JWT_SECRETKEY:bcd38b5a-95f7-4750-a4e8-a215430cc515}
    tokenPrefix: "Bearer "
    tokenExpirationAfterMinutes: 60
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
  mail:
    server: ${MAIL_SERVER:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:test@mailhog.example}
    password: ${MAIL_PASSWORD:}
  schedule:
    intervalScanRequestExpiresInMillis: 86400000
  cloudinary:
    cloud_name: ${CLOUD_NAME:dmnumhilq}
    api_key: ${CLOUDINARY_KEY:547361999122345}
    api_secret: ${CLOUDINARY_SECRET:VFQ_Gfgj6uN2BaPUFFj9RMsd_tE}