name: Send test coverage reports to codacy

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: ./gradlew check

      - name: Send code coverage report
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml